### ISSUE TITLE
Button forces thinner items

### ISSUE THREAD

**Issue by MattDemers** [christian-putzke/freshrss-pocket-button#2]
It looks like enabling the extension makes items "shorter" than they should be.

Default (no extension):

![image](https://user-images.githubusercontent.com/7098804/207780513-77e70c7f-ca7d-4cd5-8cce-d735bd074f24.png)

With extension:

![image](https://user-images.githubusercontent.com/7098804/207780565-3f26e57a-2015-4bc1-8108-7bcd247f0afa.png)

**Comment by christian-putzke** [comment]
Thanks for you report!
I'll fix this with the next release in a few days.
