### ISSUE TITLE
Article Titles Open in New Tab Instead of Expanding

### ISSUE THREAD

**Issue by calbeeb-grape** [christian-putzke/freshrss-pocket-button#4]
**Describe the bug**
When viewing the article stream, clicking on an article title should expand the article content below. However, I'm consistently experiencing an issue where clicking on the article title opens the article's origin website in a new tab.

To expand the article, I have to click on the timestamp located to the right of the article title.

I was able to expand articles as expected when I have disabled the extension.

**To Reproduce**

1. Go to 'main stream' (or any label)
2. Click on 'any article title'
3. Observe that it has opened in a new tab to the 3rd party site as the hyperlink suggested

**Expected behavior**
The article should have expanded

**FreshRSS version**
1.24.3

**Environment information**
- Database version: SQLite
- PHP version: 8.2.20
- Installation type: Docker
- -Web server type:
- Device: PC
- OS: Win11
- Browser: Edge 128, Chrome 129, Firefox 130

**Comment by christian-putzke** [comment]
Thanks for the report 😊
I just released a version which fixes that issue: https://github.com/christian-putzke/freshrss-pocket-button/releases/tag/v0.5
